# Generated by Django 3.0.5 on 2020-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_group',
            field=models.IntegerField(max_length=2),
        ),
    ]
