# Generated by Django 3.0.5 on 2020-05-06 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20200506_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_group',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
