# Generated by Django 3.0.5 on 2020-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200506_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(default=380000000000, max_length=15),
        ),
    ]
