# Generated by Django 3.0.5 on 2020-05-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200506_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=380, max_length=15, unique=True),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email', 'phone_number'), name='unique_email_and_phone_number'),
        ),
    ]
