# Generated by Django 3.0.5 on 2020-05-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200506_2153'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_email_and_phone_number',
        ),
    ]
