# Generated by Django 3.0.5 on 2020-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200510_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=380000000000, max_length=25, unique=True),
        ),
    ]
