# Generated by Django 3.0.5 on 2020-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200510_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
