# Generated by Django 3.0.5 on 2020-05-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200520_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, null=True),
        ),
    ]
