# Generated by Django 3.0.5 on 2020-05-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200506_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default=380, max_length=15),
        ),
    ]
