# Generated by Django 3.0.5 on 2020-05-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('email', 'phone_number'), name='unique_email_and_phone_number_teachers'),
        ),
    ]
