# Generated by Django 3.0.5 on 2020-05-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20200506_2205'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_email_and_phone_number_teachers',
        ),
    ]
